version: '{build}'

image: Visual Studio 2017
configuration: Release

install:
  - choco install gitversion.portable -pre -y
  - choco install codecov
  - dotnet tool install --global dotnet-sonarscanner

before_build:
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo
  - ps: if ($APPVEYOR_PULL_REQUEST_NUMBER -like "") { dotnet sonarscanner begin /k:"HGGM" /d:sonar.organization="j2ghz-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="b115314e7aa3ce0289a0691e0b78933b721288bc" /d:sonar.branch.name="$APPVEYOR_REPO_BRANCH" } else { dotnet sonarscanner begin /k:"HGGM" /d:sonar.organization="j2ghz-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="b115314e7aa3ce0289a0691e0b78933b721288bc" /d:sonar.pullrequest.base="$APPVEYOR_REPO_BRANCH" /d:sonar.pullrequest.branch="$APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH" /d:sonar.pullrequest.key="$APPVEYOR_PULL_REQUEST_NUMBER" /d:sonar.pullrequest.provider="GitHub" /d:sonar.pullrequest.github.repository="easv-d16-JSLM/HGGM"}
  - ps: msbuild /t:Restore /v:m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

build:
  verbosity: minimal
  
after_build:
  - dotnet publish -f netcoreapp2.1 -c Release HGGM

artifacts:
- path: HGGM/bin/Release/netcoreapp2.1/publish
  name: binaries

test_script:
- cmd: dotnet test "HGGM.UnitTests\HGGM.UnitTests.csproj" /p:AltCover=true
- cmd: codecov -f "HGGM.UnitTests\coverage.xml" --flag UnitTests
- cmd: dotnet test "HGGM.IntegrationTests\HGGM.IntegrationTests.csproj" /p:AltCover=true
- cmd: codecov -f "HGGM.IntegrationTests\coverage.xml" --flag IntegrationTests

after_test:
- dotnet sonarscanner end /d:sonar.login="b115314e7aa3ce0289a0691e0b78933b721288bc"
